### PR TITLE
hello git

### PR DESCRIPTION
**Pull request by grazerbeam**
be warned.... true is false yo

### CODE REVIEW

**Comment by sryabkov** [comment]
@kevinblake Hi Kevin, do you have any plans for merging this PR?

**Comment by kevinblake** [comment]
@sryabkov I do - the reason I haven't yet is partly laziness, but also because (in addition to the machine name) - it contains breaking changes to the configuration switching includeBuildDate with excludeBuildDate.  Which part of the commit are you interested in, specifically?

**Comment by sryabkov** [comment]
@kevinblake Great! The reason why I asked is that I didn't see any response to the PR, so I was wondering if the project is even alive. 
I am interested in the machine name. I personally disagree with the way the excludeBuildDate -> includeBuildDate change is currently being handled, exactly because it breaks backwards compatibility, and I didn't see any code to address that (e.g. a PowerShell script that would fix configuration). So, I think it is fair to ask @grazerbeam to either revert this change or provide a way to update configuration.

**Comment by kevinblake** [comment]
Thanks @sryabkov .  @grazerbeam As above, could you please revert the excludeBuildDate -> includeBuildDate change, and submit it as a separate PR with a method to update the the configs to maintain backwards compatibility?  Then I can merge this in right away.  Ta!

**Comment by sryabkov** [comment]
@grazerbeam @kevinblake thank you, guys. As a suggestion, it might make sense to change the title and the description of this PR...
@kevinblake Thank you for already updating the NuGet package.

**Pull request merged**
